In [6]:
import pandas as pd

In [56]:
%%time
db = pd.read_csv('From100G.csv',usecols=['tpep_picku']) #import pickup time sonly
df = pd.to_datetime(db['tpep_picku']) #convert the column to timestamp
df = df.dt.round('1min') #round the times to the nearest minute, aka drop seconds
df = df.reset_index(name = 'Time') #label the column Time

CPU times: user 260 ms, sys: 31.4 ms, total: 291 ms
Wall time: 293 ms

In [58]:
df.groupby(df["Time"]).count()

                     index
Time
2015-12-17 10:47:00    148
2015-12-17 10:48:00    331
2015-12-17 10:49:00    353
2015-12-17 10:50:00    329
2015-12-17 10:51:00    331
2015-12-17 10:52:00    332
2015-12-17 10:53:00    329
2015-12-17 10:54:00    319
2015-12-17 10:55:00    335
2015-12-17 10:56:00    340
2015-12-17 10:57:00    362
2015-12-17 10:58:00    384
2015-12-17 10:59:00    341
2015-12-17 11:00:00    354
2015-12-17 11:01:00    329
2015-12-17 11:02:00    327
2015-12-17 11:03:00    357
2015-12-17 11:04:00    376
2015-12-17 11:05:00    359
2015-12-17 11:06:00    346
2015-12-17 11:07:00    346
2015-12-17 11:08:00    353
2015-12-17 11:09:00    336
2015-12-17 11:10:00    343
2015-12-17 11:11:00    331
2015-12-17 11:12:00    369
2015-12-17 11:13:00    348
2015-12-17 11:14:00    344
2015-12-17 11:15:00    351
2015-12-17 11:16:00    329
...                    ...
2015-12-17 15:14:00    330
2015-12-17 15:15:00    280
2015-12-17 15:16:00    334
2015-12-17 15:17:00    324
2015-12-17 15:18:00    299
2015-12-17 15:19:00    311
2015-12-17 15:20:00    323
2015-12-17 15:21:00    327
2015-12-17 15:22:00    340
2015-12-17 15:23:00    284
2015-12-17 15:24:00    290
2015-12-17 15:25:00    279
2015-12-17 15:26:00    309
2015-12-17 15:27:00    264
2015-12-17 15:28:00    301
2015-12-17 15:29:00    332
2015-12-17 15:30:00    283
2015-12-17 15:31:00    324
2015-12-17 15:32:00    296
2015-12-17 15:33:00    315
2015-12-17 15:34:00    311
2015-12-17 15:35:00    272
2015-12-17 15:36:00    297
2015-12-17 15:37:00    285
2015-12-17 15:38:00    316
2015-12-17 15:39:00    280
2015-12-17 15:40:00    306
2015-12-17 15:41:00    261
2015-12-17 15:42:00    278
2015-12-17 15:43:00    231

[297 rows x 1 columns]